const vague=['appropriate','adequate','as soon as possible','fast','easy','normal','user-friendly','etc.','and/or','typically','sufficient'];
const unsafe=['always','never','all conditions','zero defects'];
const tokenize=s=>new Set(String(s||'').toLowerCase().match(/[a-z0-9]+/g)||[]);
const intersection=(a,b)=>[...a].filter(x=>b.has(x)).length;
export function validateProject(x){const e=[];for(const k of ['name','owner','domain'])if(!x?.[k]?.trim())e.push(`${k} is required.`);return e}
export function validateRequirement(x){const e=[];if(!x?.externalId?.trim())e.push('Requirement ID is required.');if(!x?.text?.trim()||x.text.trim().length<15)e.push('Requirement text must contain at least 15 characters.');return e}
export function lintRequirement(r){const text=r.text.trim(),low=text.toLowerCase(),issues=[];
 for(const term of vague)if(low.includes(term))issues.push({severity:'medium',code:'AMBIGUOUS_TERM',message:`Ambiguous term: "${term}"`,action:'Replace with a measurable condition.'});
 for(const term of unsafe)if(low.includes(term))issues.push({severity:'medium',code:'ABSOLUTE_CLAIM',message:`Absolute claim: "${term}"`,action:'Define bounded operating conditions and exceptions.'});
 if(!/\b(shall|must)\b/i.test(text))issues.push({severity:'low',code:'NORMATIVE_LANGUAGE',message:'No shall/must statement detected',action:'Clarify whether this is a binding requirement.'});
 if(!/\b(if|when|while|given|under|after|before|during)\b/i.test(text))issues.push({severity:'medium',code:'MISSING_CONDITION',message:'Trigger or operating condition is unclear',action:'Add a condition or precondition.'});
 const quantitative=/\b\d+(\.\d+)?\s*(ms|s|sec|seconds|%|v|a|ma|mb|gb|km\/h|°c|c|hz|mbps|times?)\b/i.test(text);
 if(r.type==='PERFORMANCE'&&!quantitative)issues.push({severity:'high',code:'MISSING_MEASURE',message:'Performance requirement has no measurable threshold',action:'Add value, unit, tolerance, and measurement point.'});
 if(!/[.;]$/.test(text))issues.push({severity:'low',code:'STRUCTURE',message:'Requirement does not end as a complete statement',action:'Review sentence structure.'});
 if(text.length>320)issues.push({severity:'medium',code:'COMPOUND',message:'Requirement may contain multiple obligations',action:'Split into atomic requirements.'});
 const score=Math.max(0,100-issues.reduce((s,x)=>s+({high:25,medium:12,low:5}[x.severity]),0));return{score,issues,testable:!issues.some(x=>x.severity==='high')};
}
function base(r,kind,title,pre,steps,expected,tags=[]){return{requirementIds:[r.id],kind,title,preconditions:pre,steps,expected,tags:[r.type.toLowerCase(),...tags],priority:r.priority||'MEDIUM',status:'DRAFT',source:'DETERMINISTIC',provenance:{requirementExternalId:r.externalId,generatorVersion:'1.0'}}}
export function generateTests(r){const subject=r.component||'system',condition=r.condition||'the specified operating condition',response=r.response||r.text;const tests=[
 base(r,'POSITIVE',`${r.externalId}: verify required behaviour`,[condition],[`Set ${subject} to the required initial state`,`Apply ${condition}`],`Observe and verify: ${response}`,['nominal']),
 base(r,'NEGATIVE',`${r.externalId}: reject invalid or absent trigger`,['System is operational'],[`Provide an invalid, absent, or contradictory trigger for ${condition}`],`${subject} remains in a defined safe state and reports the specified error behaviour`,['negative']),
 base(r,'ROBUSTNESS',`${r.externalId}: repeated and interrupted operation`,[condition],[`Repeat the operation`, `Interrupt and restore the triggering condition`],`No uncontrolled state, resource leak, or inconsistent response occurs`,['robustness'])
 ];
 const nums=[...r.text.matchAll(/(\d+(?:\.\d+)?)\s*(ms|s|sec|seconds|%|v|a|ma|mb|gb|km\/h|°c|hz|mbps)/ig)];
 for(const [i,m] of nums.entries()){const n=Number(m[1]),unit=m[2];for(const [label,value]of[['below',Math.max(0,n-1)],['at',n],['above',n+1]])tests.push(base(r,'BOUNDARY',`${r.externalId}: ${label} ${n} ${unit}`,[condition],[`Set relevant input to ${value} ${unit}`],`Behaviour matches the requirement boundary at ${label} ${n} ${unit}`,['boundary',`measure-${i+1}`]));}
 if(r.type==='PERFORMANCE')tests.push(base(r,'TIMING',`${r.externalId}: measure timing budget`,[condition],[`Instrument start and completion timestamps`,`Execute representative workload`],`Measured timing meets every declared threshold and evidence is retained`,['performance']));
 if(r.cybersecurityRelevant)tests.push(base(r,'SECURITY',`${r.externalId}: unauthorised and malformed input`,['Security controls enabled'],[`Send unauthorised, malformed, and replayed requests`],`Request is rejected, security event is recorded, and availability remains within budget`,['cybersecurity']));
 if(r.safetyRelevant)tests.push(base(r,'SAFETY',`${r.externalId}: fault response and safe state`,['Fault injection environment approved'],[`Inject loss, corruption, delay, and out-of-range conditions`],`Safety mechanism detects the fault and reaches the defined safe/degraded state`,['safety']));return tests;
}
export function similarity(a,b){const A=tokenize(`${a.title} ${a.steps?.join(' ')} ${a.expected}`),B=tokenize(`${b.title} ${b.steps?.join(' ')} ${b.expected}`);return A.size||B.size?intersection(A,B)/Math.max(1,new Set([...A,...B]).size):0}
export function duplicatePairs(tests,threshold=.72){const out=[];for(let i=0;i<tests.length;i++)for(let j=i+1;j<tests.length;j++){const score=similarity(tests[i],tests[j]);if(score>=threshold)out.push({leftId:tests[i].id,rightId:tests[j].id,score:Number(score.toFixed(2))})}return out}
export function assessProject(p){const req=p.requirements||[],tests=p.tests||[],approved=tests.filter(t=>t.status==='APPROVED'),covered=new Set(tests.flatMap(t=>t.requirementIds||[])),approvedCovered=new Set(approved.flatMap(t=>t.requirementIds||[])),duplicates=duplicatePairs(tests);const findings=[];const untestable=req.filter(r=>!r.lint?.testable);const uncovered=req.filter(r=>!covered.has(r.id));const unapproved=req.filter(r=>!approvedCovered.has(r.id));if(untestable.length)findings.push({severity:'high',title:`${untestable.length} requirements have high-severity quality issues`,action:'Clarify the requirements before baselining tests.'});if(uncovered.length)findings.push({severity:'high',title:`${uncovered.length} requirements have no generated tests`,action:'Generate and review tests for every requirement.'});if(unapproved.length)findings.push({severity:'medium',title:`${unapproved.length} requirements lack approved tests`,action:'Complete qualified human review.'});if(duplicates.length)findings.push({severity:'medium',title:`${duplicates.length} possible duplicate test pairs`,action:'Review, merge, or justify duplicated coverage.'});return{status:findings.some(x=>x.severity==='high')?'GAPS_IDENTIFIED':req.length&&approvedCovered.size===req.length?'BASELINE_CANDIDATE':'REVIEW_REQUIRED',metrics:{requirements:req.length,averageQuality:req.length?Math.round(req.reduce((s,r)=>s+r.lint.score,0)/req.length):0,tests:tests.length,approvedTests:approved.length,requirementCoverage:req.length?Math.round(covered.size/req.length*100):0,approvedCoverage:req.length?Math.round(approvedCovered.size/req.length*100):0,duplicatePairs:duplicates.length},findings,duplicates,disclaimer:'Generated tests are drafts. Competent human review and execution evidence are mandatory.'}}
