import http from'node:http';import{readFile}from'node:fs/promises';import path from'node:path';import{fileURLToPath}from'node:url';import{Store,id}from'./store.mjs';import{assessProject,generateTests,lintRequirement,validateProject,validateRequirement}from'./engine.mjs';import{augmentRequirement,configured}from'./ai.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),store=new Store(path.resolve(process.env.DATA_DIR||path.join(root,'data')));await store.init();const port=Number(process.env.PORT||3000),mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json','.csv':'text/csv; charset=utf-8'};
async function body(r){let x='';for await(const c of r){x+=c;if(x.length>2e6)throw Object.assign(new Error('Request too large'),{status:413})}return x?JSON.parse(x):{}}function send(r,s,x,t='application/json; charset=utf-8'){r.writeHead(s,{'content-type':t,'cache-control':'no-store','x-content-type-options':'nosniff','x-frame-options':'DENY'});r.end(t.startsWith('application/json')?JSON.stringify(x):x)}function audit(p,a,actor='user',detail={}){p.audit.push({id:id(),at:new Date().toISOString(),action:a,actor,detail})}const esc=x=>`"${String(x??'').replaceAll('"','""')}"`;
async function route(req,res){const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&u.pathname==='/api/health')return send(res,200,{status:'ok',service:'Req2Test AI',aiConfigured:configured(),time:new Date().toISOString()});if(req.method==='GET'&&u.pathname==='/api/projects')return send(res,200,(await store.list()).map(p=>({id:p.id,name:p.name,domain:p.domain,owner:p.owner,updatedAt:p.updatedAt,assessment:assessProject(p)})));
 if(req.method==='POST'&&u.pathname==='/api/projects'){const x=await body(req),e=validateProject(x);if(e.length)return send(res,400,{errors:e});const p=await store.create({name:x.name.trim(),owner:x.owner.trim(),domain:x.domain.trim(),description:x.description||'',requirements:[],tests:[],reviews:[],audit:[]});audit(p,'PROJECT_CREATED',p.owner);await store.save(p);return send(res,201,{...p,assessment:assessProject(p)})}
 const m=u.pathname.match(/^\/api\/projects\/([a-f0-9-]+)(?:\/(requirements|generate|tests|reviews|report|export\.csv))?$/i);if(m&&req.method==='GET'&&!m[2]){const p=await store.get(m[1]);return send(res,200,{...p,assessment:assessProject(p)})}if(!m)return req.method==='GET'?staticFile(u,res):send(res,404,{error:'Not found'});const p=await store.get(m[1]);if(req.method==='GET'&&m[2]==='report')return send(res,200,{schemaVersion:'1.0',project:p,assessment:assessProject(p)});if(req.method==='GET'&&m[2]==='export.csv'){const rows=[['Test ID','Requirement IDs','Kind','Title','Preconditions','Steps','Expected','Priority','Status','Source'],...p.tests.map(t=>[t.id,(t.requirementIds||[]).join('|'),t.kind,t.title,(t.preconditions||[]).join(' | '),(t.steps||[]).join(' | '),t.expected,t.priority,t.status,t.source])];return send(res,200,rows.map(r=>r.map(esc).join(',')).join('\n'),'text/csv; charset=utf-8')}if(req.method!=='POST')return send(res,405,{error:'Method not allowed'});const x=await body(req);
 if(m[2]==='requirements'){const e=validateRequirement(x);if(e.length)return send(res,400,{errors:e});if(p.requirements.some(r=>r.externalId===x.externalId.trim()))return send(res,409,{error:'Requirement ID already exists.'});const r={id:id(),externalId:x.externalId.trim(),text:x.text.trim(),type:x.type||'FUNCTIONAL',priority:x.priority||'MEDIUM',component:x.component||'',condition:x.condition||'',response:x.response||'',safetyRelevant:Boolean(x.safetyRelevant),cybersecurityRelevant:Boolean(x.cybersecurityRelevant),status:'DRAFT'};r.lint=lintRequirement(r);p.requirements.push(r);audit(p,'REQUIREMENT_ADDED',x.actor,{requirementId:r.id,quality:r.lint.score})}
 if(m[2]==='generate'){const ids=x.requirementIds?.length?x.requirementIds:p.requirements.map(r=>r.id);for(const r of p.requirements.filter(r=>ids.includes(r.id))){const existing=p.tests.filter(t=>t.requirementIds?.includes(r.id));if(existing.length&&!x.regenerate)continue;let tests=generateTests(r);if(x.useAI)tests=await augmentRequirement(r,tests);for(const t of tests)p.tests.push({id:id(),createdAt:new Date().toISOString(),...t})}audit(p,'TESTS_GENERATED',x.actor,{requirementIds:ids,useAI:Boolean(x.useAI&&configured())})}
 if(m[2]==='tests'){const t=p.tests.find(v=>v.id===x.testId);if(!t)return send(res,404,{error:'Test not found.'});for(const k of ['title','expected','priority','status'])if(x[k]!==undefined)t[k]=x[k];if(Array.isArray(x.preconditions))t.preconditions=x.preconditions;if(Array.isArray(x.steps))t.steps=x.steps;audit(p,'TEST_UPDATED',x.actor,{testId:t.id,status:t.status})}
 if(m[2]==='reviews'){if(!x.reviewer?.trim()||!['APPROVED','REWORK','REJECTED'].includes(x.disposition))return send(res,400,{error:'Reviewer and valid disposition are required.'});const ids=x.testIds?.length?x.testIds:p.tests.map(t=>t.id);for(const t of p.tests.filter(t=>ids.includes(t.id)))t.status=x.disposition;const r={id:id(),reviewer:x.reviewer.trim(),disposition:x.disposition,testIds:ids,notes:x.notes||'',at:new Date().toISOString()};p.reviews.push(r);audit(p,'REVIEW_RECORDED',r.reviewer,{reviewId:r.id,disposition:r.disposition,count:ids.length})}
 await store.save(p);return send(res,200,{...p,assessment:assessProject(p)})}
async function staticFile(u,res){const f=u.pathname==='/'?'index.html':u.pathname.replace(/^\/+/,''),t=path.join(root,'public',path.normalize(f));if(!t.startsWith(path.join(root,'public')))return send(res,403,{error:'Forbidden'});try{return send(res,200,await readFile(t),mime[path.extname(t)]||'application/octet-stream')}catch{return send(res,404,{error:'Not found'})}}
http.createServer((q,s)=>route(q,s).catch(e=>{console.error(e);send(s,e.status||500,{error:e.message||'Unexpected error'})})).listen(port,'0.0.0.0',()=>console.log(`Req2Test AI listening on ${port}`));
